### ISSUE TITLE
Select Estado e cidade

### ISSUE THREAD

**Issue by droliv** [CodeSolidario/petsheroes-front#1]
Precisamos desenvolver no HomeComponent um filtro que preencha o combo cidade de acordo com o valor selecionado no combo estado. Tem alguns valores de teste, mas precisamos mostrar todos os estados e cidades do Brasil.

**Comment by angeloreale** [comment]
Seria legal fazer um endpoint na API que receba a sigla do estado como parametro e devolva as cidades em JSON. Posso cuidar disso. Não manjo de Angular nem TS, poderia implementar em vanilla, React ou Vue, serve? Qual a linguagem do back? Node? Posso ajudar com o endpoint também.

**Comment by droliv** [comment]
Olá Angelo bom dia, tudo bem?
Bom, eu baixei a brach pra testar e apresentou um alguns erros aqui, não sei se você conseguiu rodar normal essas alterações.
Aqui não rodou e apresentou os seguintes erros:

ERROR in src/app/home/home.component.ts(25,39): error TS2339: Property 'value' does not exist on type 'EventTarget'.
src/app/home/home.component.ts(30,15): error TS2339: Property 'disabled' does not exist on type 'Element'.
src/app/home/home.component.ts(41,19): error TS2339: Property 'disabled' does not exist on type 'Element'.
src/app/home/home.component.ts(47,15): error TS2339: Property 'disabled' does not exist on type 'Element'.
src/app/home/home.component.ts(59,17): error TS2339: Property 'disabled' does not exist on type 'Element'.

Poderia me ajudar sobre isso?

**Comment by angeloreale** [comment]
Acho que são erros referentes ao TS, ele não reconhece as propriedades 'Element.value' e 'Element.disabled' do javascript. Como não conheço muito de TS nem de Angular, não soube como criar um JS separado e carregá-lo no sistema. Vocë saberia como fazer isso?

**Comment by droliv** [comment]
Angelo eu não consegui resolver porque meu conhecimento de integração do javascript com o typescript é um pouco limitado, acabou ficando confuso pra mim, vou tentar verificar uma forma mais simples pra fazer isso.

**Comment by angeloreale** [comment]
Acho que dá pra fazer com imports, estive pensando hoje. Vou tentar e ver se funciona.
